# Building plans
# Sans
[buildPlans.iosevka]
family = "Iosevka"

[buildPlans.iosevka-term]
family = "Iosevka Term"
design = ["term"]

[buildPlans.iosevka-type]
family = "Iosevka Type"
design = ["type"]

[buildPlans.iosevka-term-lig]
family = "Iosevka TermLig"
design = ["termlig"]

[buildPlans.iosevka-cc]
family = "IosevkaCC"
design = ["cc"]

# Slab
[buildPlans.iosevka-slab]
family = "Iosevka Slab"
design = ["slab"]

[buildPlans.iosevka-term-slab]
family = "Iosevka Term Slab"
design = ["term", "slab"]

[buildPlans.iosevka-type-slab]
family = "Iosevka Type Slab"
design = ["type", "slab"]

[buildPlans.iosevka-term-lig-slab]
family = "Iosevka TermLig Slab"
design = ["termlig", "slab"]

[buildPlans.iosevka-cc-slab]
family = "IosevkaCC Slab"
design = ["cc", "slab"]

# Crisp
[buildPlans.iosevka-crisp]
family  = "Iosevka Crisp"
design  = ["shape-straight-bar", "v-at-fourfold"]

[buildPlans.iosevka-term-crisp]
family  = "Iosevka Term Crisp"
design  = ["term", "shape-straight-bar", "v-at-fourfold"]

[buildPlans.iosevka-type-crisp]
family  = "Iosevka Type Crisp"
design  = ["type", "shape-straight-bar", "v-at-fourfold"]

[buildPlans.iosevka-term-lig-crisp]
family  = "Iosevka TermLig Crisp"
design  = ["termlig", "shape-straight-bar", "v-at-fourfold"]

[buildPlans.iosevka-cc-crisp]
family  = "IosevkaCC Crisp"
design  = ["cc", "shape-straight-bar", "v-at-fourfold"]

# Crisp Slab
[buildPlans.iosevka-crisp-slab]
family  = "Iosevka Crisp Slab"
design  = ["slab", "shape-straight-bar", "v-at-fourfold"]

[buildPlans.iosevka-term-crisp-slab]
family  = "Iosevka Term Crisp Slab"
design  = ["term", "slab", "shape-straight-bar", "v-at-fourfold"]

[buildPlans.iosevka-type-crisp-slab]
family  = "Iosevka Type Crisp Slab"
design  = ["type", "slab", "shape-straight-bar", "v-at-fourfold"]

[buildPlans.iosevka-term-lig-crisp-slab]
family  = "Iosevka TermLig Crisp Slab"
design  = ["termlig", "slab", "shape-straight-bar", "v-at-fourfold"]

[buildPlans.iosevka-cc-crisp-slab]
family  = "IosevkaCC Crisp Slab"
design  = ["cc", "slab", "shape-straight-bar", "v-at-fourfold"]

# SSxx
[buildPlans.iosevka-ss01]
family = "Iosevka SS01"
design = ["ss01"]

[buildPlans.iosevka-term-ss01]
family = "Iosevka Term SS01"
design = ["term", "ss01"]

[buildPlans.iosevka-ss02]
family = "Iosevka SS02"
design = ["ss02"]

[buildPlans.iosevka-term-ss02]
family = "Iosevka Term SS02"
design = ["term", "ss02"]

[buildPlans.iosevka-ss03]
family = "Iosevka SS03"
design = ["ss03"]

[buildPlans.iosevka-term-ss03]
family = "Iosevka Term SS03"
design = ["term", "ss03"]

[buildPlans.iosevka-ss04]
family = "Iosevka SS04"
design = ["ss04"]

[buildPlans.iosevka-term-ss04]
family = "Iosevka Term SS04"
design = ["term", "ss04"]

[buildPlans.iosevka-ss05]
family = "Iosevka SS05"
design = ["ss05"]

[buildPlans.iosevka-term-ss05]
family = "Iosevka Term SS05"
design = ["term", "ss05"]

[buildPlans.iosevka-ss06]
family = "Iosevka SS06"
design = ["ss06"]

[buildPlans.iosevka-term-ss06]
family = "Iosevka Term SS06"
design = ["term", "ss06"]

[buildPlans.iosevka-ss07]
family = "Iosevka SS07"
design = ["ss07"]

[buildPlans.iosevka-term-ss07]
family = "Iosevka Term SS07"
design = ["term", "ss07"]

[buildPlans.iosevka-ss08]
family = "Iosevka SS08"
design = ["ss08"]

[buildPlans.iosevka-term-ss08]
family = "Iosevka Term SS08"
design = ["term", "ss08"]

[buildPlans.iosevka-ss09]
family = "Iosevka SS09"
design = ["ss09"]

[buildPlans.iosevka-term-ss09]
family = "Iosevka Term SS09"
design = ["term", "ss09"]

[buildPlans.iosevka-ss10]
family = "Iosevka SS10"
design = ["ss10"]

[buildPlans.iosevka-term-ss10]
family = "Iosevka Term SS10"
design = ["term", "ss10"]

[buildPlans.iosevka-ss11]
family = "Iosevka SS11"
design = ["ss11"]

[buildPlans.iosevka-term-ss11]
family = "Iosevka Term SS11"
design = ["term", "ss11"]

[buildPlans.iosevka-aile]
family  = "Iosevka Aile"
design  = ["type", "shape-straight-bar", "v-at-fourfold", "v-j-narrow", 'v-capital-i-straight', 'v-capital-j-straight', 'v-g-singlestorey', 'v-r-narrow', "no-cv-ss", "no-ligation"]
upright = ["v-i-line", "v-l-line", 'v-f-narrow', 'v-t-narrow']
italic  = ["v-i-line", "v-l-line", 'v-f-narrow', 'v-t-narrow']
oblique = ["v-i-line", "v-l-line", 'v-f-narrow', 'v-t-narrow']

[buildPlans.iosevka-aile.post]
design = ['wd-extended', "diversity-2"]

[buildPlans.iosevka-etoile]
family  = "Iosevka Etoile"
design  = ["type", "slab", "shape-straight-bar", "diversity-1", "v-at-fourfold", 'v-j-serifed', 'no-cv-ss', "no-cv-ss", "no-ligation"]
upright = ['v-i-serifed', 'v-l-serifed']
italic  = ['v-i-italic', 'v-l-italic']
oblique = ['v-i-serifed', 'v-l-serifed']

[buildPlans.iosevka-extended]
family  = "Iosevka"
design  = ["shape-straight-bar"]

[buildPlans.iosevka-extended.post]
design = ['wd-extended', 'menu-subfamily-extended']

[buildPlans.iosevka-slab-extended]
family  = "Iosevka Slab"
design  = ["slab", "shape-straight-bar"]

[buildPlans.iosevka-slab-extended.post]
design = ['wd-extended', 'menu-subfamily-extended']

# Export plans
# This mapping affects the process of creating ZIP archives only
[exportPlans]

# Standard set
01-iosevka = "iosevka"
02-iosevka-term = "iosevka-term"
03-iosevka-type = "iosevka-type"
04-iosevka-term-lig = "iosevka-term-lig"
05-iosevka-slab = "iosevka-slab"
06-iosevka-term-slab = "iosevka-term-slab"
07-iosevka-type-slab = "iosevka-type-slab"
08-iosevka-term-lig-slab = "iosevka-term-lig-slab"
09-iosevka-crisp = "iosevka-crisp"
10-iosevka-term-crisp = "iosevka-term-crisp"
11-iosevka-type-crisp = "iosevka-type-crisp"
12-iosevka-term-lig-crisp = "iosevka-term-lig-crisp"
13-iosevka-crisp-slab = "iosevka-crisp-slab"
14-iosevka-term-crisp-slab = "iosevka-term-crisp-slab"
15-iosevka-type-crisp-slab = "iosevka-type-crisp-slab"
16-iosevka-term-lig-crisp-slab = "iosevka-term-lig-crisp-slab"

# "CC" variants (deprecated -- will be removed in next release)
iosevka-cc-DEPRECATED = "iosevka-cc"
iosevka-cc-slab-DEPRECATED = "iosevka-cc-slab"
iosevka-cc-crisp-DEPRECATED = "iosevka-cc-crisp"
iosevka-cc-slab-crisp-DEPRECATED = "iosevka-cc-slab-crisp"

# Style set variants
iosevka-ss01 = "iosevka-ss01"
iosevka-term-ss01 = "iosevka-term-ss01"
iosevka-ss02 = "iosevka-ss02"
iosevka-term-ss02 = "iosevka-term-ss02"
iosevka-ss03 = "iosevka-ss03"
iosevka-term-ss03 = "iosevka-term-ss03"
iosevka-ss04 = "iosevka-ss04"
iosevka-term-ss04 = "iosevka-term-ss04"
iosevka-ss05 = "iosevka-ss05"
iosevka-term-ss05 = "iosevka-term-ss05"
iosevka-ss06 = "iosevka-ss06"
iosevka-term-ss06 = "iosevka-term-ss06"
iosevka-ss07 = "iosevka-ss07"
iosevka-term-ss07 = "iosevka-term-ss07"
iosevka-ss08 = "iosevka-ss08"
iosevka-term-ss08 = "iosevka-term-ss08"
iosevka-ss09 = "iosevka-ss09"
iosevka-term-ss09 = "iosevka-term-ss09"
iosevka-ss10 = "iosevka-ss10"
iosevka-term-ss10 = "iosevka-term-ss10"
iosevka-ss11 = "iosevka-ss11"
iosevka-term-ss11 = "iosevka-term-ss11"

# Experimental variants
experimental-iosevka-aile = "iosevka-aile"
experimental-iosevka-etoile = "iosevka-etoile"
experimental-iosevka-extended = "iosevka-extended"
experimental-iosevka-slab-extended = "iosevka-slab-extended"

# TTC collection plans
[collectPlans.iosevka]
from = [
	"iosevka",
	"iosevka-term",
	"iosevka-type",
	"iosevka-term-lig"
]

[collectPlans.iosevka-slab]
from = [
	"iosevka-slab",
	"iosevka-term-slab",
	"iosevka-type-slab",
	"iosevka-term-lig-slab"
]

[collectPlans.iosevka-crisp]
from = [
	"iosevka-crisp",
	"iosevka-term-crisp",
	"iosevka-type-crisp",
	"iosevka-term-lig-crisp"
]

[collectPlans.iosevka-crisp-slab]
from = [
	"iosevka-crisp-slab",
	"iosevka-term-crisp-slab",
	"iosevka-type-crisp-slab",
	"iosevka-term-lig-crisp-slab"
]

# Weight mappings (style => shape weight, CSS weight)
#   Shape weight : affects the shape of the glyphs
#   CSS weight   : affects the font menu name and webfont CSS
[weights.thin]
shape = 100
menu  = 100
css   = 100

[weights.extralight]
shape = 200
menu  = 200
css   = 200

[weights.light]
shape = 300
menu  = 300
css   = 300

[weights.regular]
shape = 400
menu  = 400
css   = 400

[weights.medium]
shape = 500
menu  = 500
css   = 500

[weights.semibold]
shape = 600
menu  = 600
css   = 600

[weights.bold]
shape = 700
menu  = 700
css   = 700

[weights.extrabold]
shape = 800
menu  = 800
css   = 800

[weights.heavy]
shape = 900
menu  = 900
css   = 900

# Slant mappings (style => CSS)
# NOTE: This mapping does NOT affect the font's metadata, only affects
#       the webfont CSS. Change `parameters.toml` instead.
[slants]
upright = "normal"
oblique = "oblique"
italic = "italic"
