[buildPlans.i3]
family = "i3"
design = [
	"ss20",
    "v-a-doublestorey",
	"v-f-tailed",
    "v-g-doublestorey",
	"v-y-cursive",
    "v-asterisk-low",
    "v-percent-dots",
    "v-underscore-low",
    "no-ligation"
]
hintParams = ["-a", "sss"]                          # Optional custom parameters for ttfautohint


[buildPlans.i3.weights.regular]
shape = 400  # Weight for glyph shapes
menu  = 400  # Weight for menu name
css   = 400  # Weight for webfont CSS

[buildPlans.i3.slants]
upright = "normal"
italic = "italic"
# oblique = "oblique"

[buildPlans.i3.widths.normal]
shape = 5
menu  = 5
css   = "normal"


[buildPlans.isk]
family = "isk"
design = [
	"ss20",
    "v-a-doublestorey",
	"v-f-tailed",
    "v-g-doublestorey",
	"v-y-cursive",
    "v-asterisk-low",
    "v-underscore-low",
    "v-percent-dots",
    "no-ligation"
]
hintParams = ["-a", "sss"]


[buildPlans.isk.weights.regular]
shape = 400  # Weight for glyph shapes
menu  = 400  # Weight for menu name
css   = 400  # Weight for webfont CSS

[buildPlans.isk.slants]
upright = "normal"
italic = "italic"
# oblique = "oblique"

[buildPlans.isk.widths.normal]
shape = 7
menu  = 5
css   = "normal"